"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class dog_in_frame_info(object):

    __slots__ = ["dog_coord", "dog_orientation"]

    __typenames__ = ["float", "float"]

    __dimensions__ = [[3], [3]]

    def __init__(self):
        self.dog_coord = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.dog_orientation = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(dog_in_frame_info._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.dog_coord[:3]))
        buf.write(struct.pack('>3f', *self.dog_orientation[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dog_in_frame_info._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dog_in_frame_info._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = dog_in_frame_info()
        self.dog_coord = struct.unpack('>3f', buf.read(12))
        self.dog_orientation = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if dog_in_frame_info in parents: return 0
        tmphash = (0x7ce1accbcdf9bb2e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if dog_in_frame_info._packed_fingerprint is None:
            dog_in_frame_info._packed_fingerprint = struct.pack(">Q", dog_in_frame_info._get_hash_recursive([]))
        return dog_in_frame_info._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", dog_in_frame_info._get_packed_fingerprint())[0]

