"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class dog_feedback_info(object):
    """
    RC command information is from dog
    need to send back to remote PC(with realsense)
    Only intended for debugging purpose
    """

    __slots__ = ["dog_target_coord", "dog_action"]

    __typenames__ = ["float", "float"]

    __dimensions__ = [[2], [2]]

    def __init__(self):
        self.dog_target_coord = [ 0.0 for dim0 in range(2) ]
        """ LCM Type: float[2] """
        self.dog_action = [ 0.0 for dim0 in range(2) ]
        """ LCM Type: float[2] """

    def encode(self):
        buf = BytesIO()
        buf.write(dog_feedback_info._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2f', *self.dog_target_coord[:2]))
        buf.write(struct.pack('>2f', *self.dog_action[:2]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dog_feedback_info._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dog_feedback_info._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = dog_feedback_info()
        self.dog_target_coord = struct.unpack('>2f', buf.read(8))
        self.dog_action = struct.unpack('>2f', buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if dog_feedback_info in parents: return 0
        tmphash = (0x9f215ec3321c368) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if dog_feedback_info._packed_fingerprint is None:
            dog_feedback_info._packed_fingerprint = struct.pack(">Q", dog_feedback_info._get_hash_recursive([]))
        return dog_feedback_info._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", dog_feedback_info._get_packed_fingerprint())[0]

